services:
  mysql:
    image: mysql:latest
    container_name: mysql_db_lab6    
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
            
    ports:
      - "3306:3306"
    # volumes:
    #   - mysql_data:/var/lib/mysql
    

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_lab06    
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "9000:80"

# volumes:
#   mysql_data:

